"use client";

import React, { useState, useRef, useEffect } from 'react';
import { Sparkles } from 'lucide-react';
import { generateQuiz, Quiz } from '@/lib/llm-service';
import QuizCard from './QuizCard';
import { useProgress } from '@/hooks/useProgress';

interface AIQuizGeneratorProps {
    courseId: string;
    lessonId: string;
    topic: string;
    context: string;
}

export default function AIQuizGenerator({ courseId, lessonId, topic }: AIQuizGeneratorProps) {
    const [quiz, setQuiz] = useState<Quiz | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const { markLessonComplete } = useProgress();
    const containerRef = useRef<HTMLDivElement>(null);

    const handleGenerate = async () => {
        setLoading(true);
        setError(null);
        try {
            const newQuiz = await generateQuiz(courseId, lessonId);
            setQuiz(newQuiz);
        } catch (err) {
            setError("Failed to generate quiz. Please try again.");
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    // Scroll to top removed to prevent page jumping


    const handleVerify = (explanation: string) => {
        // Placeholder for future verification logic
        console.log("Verified:", explanation);
    };

    const handleComplete = () => {
        markLessonComplete(courseId, lessonId);
    };

    return (
        <div ref={containerRef} className="my-12 p-8 glass-panel border-2 border-indigo-400/30 rounded-2xl shadow-2xl relative z-10">
            <div className="text-center mb-8">
                <div className="inline-flex items-center justify-center w-12 h-12 bg-indigo-500/20 backdrop-blur-sm rounded-full shadow-lg mb-4 text-indigo-400">
                    <Sparkles size={24} />
                </div>
                <h2 className="text-2xl font-bold text-text-primary mb-2">Test Your Knowledge</h2>
                <p className="text-text-secondary max-w-md mx-auto">
                    Ready to check your understanding? Generate a personalized quiz based on this lesson using AI.
                </p>
            </div>

            {!quiz ? (
                <div className="flex justify-center">
                    <button
                        onClick={handleGenerate}
                        disabled={loading}
                        className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-3 rounded-lg font-semibold transition-all transform hover:scale-105 shadow-lg shadow-indigo-200 disabled:opacity-70 disabled:cursor-not-allowed disabled:transform-none"
                    >
                        {loading ? (
                            <>
                                <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                Generating Quiz...
                            </>
                        ) : (
                            <>
                                <Sparkles size={20} />
                                Generate AI Quiz
                            </>
                        )}
                    </button>
                </div>
            ) : (
                <div className="max-w-2xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
                    {loading ? (
                        <div className="flex flex-col items-center justify-center py-12">
                            <div className="w-8 h-8 border-4 border-indigo-200 border-t-indigo-600 rounded-full animate-spin mb-4" />
                            <p className="text-indigo-600 font-medium">Generating new question...</p>
                        </div>
                    ) : (
                        <>
                            <QuizCard quiz={quiz} onVerify={handleVerify} onComplete={handleComplete} />
                            <div className="text-center mt-6">
                                <button
                                    onClick={handleGenerate}
                                    className="text-sm text-indigo-600 hover:text-indigo-800 font-medium flex items-center justify-center gap-2 mx-auto"
                                >
                                    <Sparkles size={16} />
                                    Generate Another Question
                                </button>
                                {quiz.model && (
                                    <p className="text-xs text-gray-400 mt-2">
                                        Generated by {quiz.model}
                                    </p>
                                )}
                            </div>
                        </>
                    )}
                </div>
            )
            }

            {
                error && (
                    <p className="text-center text-red-500 mt-4 text-sm">{error}</p>
                )
            }
        </div >
    );
}
